title: Babaganush
baseurl: /
collections:
  posts:
    permalink: '/posts/:title/'
permalink: '/:title/'
layout_style: grid
palette: green
header:
  title: Babaganush
  logo_img: ''
  has_nav: true
footer:
  content: '&copy; All rights reserved.'
  links: []
  has_social: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
